

package Quiz_Game.rmi.client;

import Quiz_Game.Interface.Interface;
import java.awt.HeadlessException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * This program is to add the question into the database. 
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class A_AddNewQuestion extends javax.swing.JFrame {

    /**
     * Creates new form addNewQuestion
     */
    public A_AddNewQuestion() {
        initComponents();
        
        try {
            /*The suspect that this block of statement can throw
        *exception so we handled it by placing these statements
        *inside try and handled the exception in catch block
             */

            Interface b = (Interface) Naming.lookup("rmi://localhost:1099/Server"); //It calls naming lookup and url  

            CachedRowSet idDetails = b.getquestionId(); // It gets the results in cachedRowSet

            if (idDetails.next()) {
                int id = idDetails.getInt(1);
                id = id + 1;
                String str = String.valueOf(id);
                jLabel5.setText(str);
            } else {
                jLabel5.setText("1");
            }

        } catch (MalformedURLException | NotBoundException | RemoteException | SQLException e) {
            /*
        * This block will only execute if any  exception occurs in try block
             */
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        answer_txtfield = new javax.swing.JTextField();
        opt2_txtfield = new javax.swing.JTextField();
        opt3_txtfield = new javax.swing.JTextField();
        opt4_txtfield = new javax.swing.JTextField();
        Question_txtfield = new javax.swing.JTextField();
        opt1_txtfield = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(410, 300));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 40)); // NOI18N
        jLabel2.setText("ADD NEW QUESTION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 22, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Question ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Question:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel7.setText("Option 1:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel8.setText("Option 2:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel9.setText("Option 3:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel10.setText("Option 4:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Answer:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        answer_txtfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        answer_txtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(answer_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 700, -1));

        opt2_txtfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        opt2_txtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(opt2_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 700, -1));

        opt3_txtfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        opt3_txtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        opt3_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_txtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(opt3_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 700, -1));

        opt4_txtfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        opt4_txtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(opt4_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 700, -1));

        Question_txtfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Question_txtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Question_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question_txtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(Question_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 700, -1));

        opt1_txtfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        opt1_txtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(opt1_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 700, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 1070, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Save.setBackground(new java.awt.Color(255, 255, 255));
        Save.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Save.setText("Save");
        Save.setBorder(new javax.swing.border.MatteBorder(null));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 255, 255));
        Clear.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Clear.setText("Clear");
        Clear.setBorder(new javax.swing.border.MatteBorder(null));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-black-32.png"))); // NOI18N
        close_btn.setOpaque(false);
        close_btn.setContentAreaFilled(false);
        close_btn.setBorderPainted(false);
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(close_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Question_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question_txtfieldActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:

        boolean insert = false;

        String id = jLabel5.getText();
        String name = Question_txtfield.getText();
        String opt1 = opt1_txtfield.getText();
        String opt2 = opt2_txtfield.getText();
        String opt3 = opt3_txtfield.getText();
        String opt4 = opt4_txtfield.getText();
        String answer = answer_txtfield.getText();

        try {
            /*The suspect that this block of statement can throw
            * exception so we handled it by placing these statements
            * inside try and handled the exception in catch block
             */

            Interface b = (Interface) Naming.lookup("rmi://localhost/Server"); //It calls naming lookup and url
            insert = b.InsertQuestion(id, name, opt1, opt2, opt3, opt4, answer);

            if (insert == true) {
                //This Popup message will help to admin for inserting the data  
                int responseInsert = JOptionPane.showConfirmDialog(this, "Do you want to continue action ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                // If yes, the data will be added to the database 
                if (responseInsert == JOptionPane.YES_OPTION) {
                    //This will generate Successfully inserted messege 
                    JOptionPane.showMessageDialog(this, "Successfully Inserted", "Alert", JOptionPane.WARNING_MESSAGE);
                    JFrame jf = new JFrame();
                    jf.setAlwaysOnTop(true);
                    setVisible(false);
                    new A_AddNewQuestion().setVisible(true);

                } else {
                    //If no, the data won't be added to the database
                    JOptionPane.showMessageDialog(this, "Data Insertion Cancelled!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Insert Data!", "Failure", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (HeadlessException | SecurityException | NotBoundException | RemoteException ex) {
            /*
          *This block will only execute if any  exception occurs in try block
             */
            JOptionPane.showMessageDialog(null, "Error! " + ex, "Bug!", JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            /*
          *This block will only execute if any  exception occurs in try block
             */
            Logger.getLogger(A_AddNewQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void opt3_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3_txtfieldActionPerformed
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // This code segment is used to clear the textfields
        Question_txtfield.setText("");
        opt1_txtfield.setText("");
        opt2_txtfield.setText("");
        opt3_txtfield.setText("");
        opt4_txtfield.setText("");
        answer_txtfield.setText("");
            
        
    }//GEN-LAST:event_ClearActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // This code segment is used to close  the admin panel
        AdminHomePanel.open=0;
        setVisible(false);
    }//GEN-LAST:event_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_AddNewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Question_txtfield;
    private javax.swing.JButton Save;
    private javax.swing.JTextField answer_txtfield;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField opt1_txtfield;
    private javax.swing.JTextField opt2_txtfield;
    private javax.swing.JTextField opt3_txtfield;
    private javax.swing.JTextField opt4_txtfield;
    // End of variables declaration//GEN-END:variables
}
