package Quiz_Game.rmi.client;

import Quiz_Game.Interface.Interface;
import java.awt.HeadlessException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * This program is to update the question.  
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class A_Update_Question extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Question
     */
    public A_Update_Question() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        QUES = new javax.swing.JTextField();
        OP1 = new javax.swing.JTextField();
        OP2 = new javax.swing.JTextField();
        OP3 = new javax.swing.JTextField();
        OP4 = new javax.swing.JTextField();
        AN = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(410, 300));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        QID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(QID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Search");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 106, 60, 30));

        QUES.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        QUES.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(QUES, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 770, -1));

        OP1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        OP1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(OP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 770, -1));

        OP2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        OP2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(OP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 770, -1));

        OP3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        OP3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(OP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 770, -1));

        OP4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        OP4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(OP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 770, -1));

        AN.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        AN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(AN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 770, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 90, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("QUESTION ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 103, 172, 29));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 40)); // NOI18N
        jLabel3.setText("UPDATE QUESTION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel4.setText("OPTION 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 106, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("QUESTION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 106, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel6.setText("OPTION 4:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 106, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel7.setText("OPTION 3:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 106, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel8.setText("ANSWER:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 106, 29));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel9.setText("OPTION 1:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 106, 29));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close-black-32.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           String id=QID.getText(); 
    
   try {  
       /*The suspect that this block of statement can throw
        *exception so we handled it by placing these statements
        *inside try and handled the exception in catch block
        */
       
        Interface a = (Interface) Naming.lookup("rmi://localhost:1099/Server");////It calls naming lookup and url  
            
        CachedRowSet questionDetails=a.getquestions(id); //getting  questionDetails in cachedRowSet
                   
        if(questionDetails.first())
        {   
            QUES.setText(questionDetails.getString(2));
            OP1.setText(questionDetails.getString(3));
            OP2.setText(questionDetails.getString(4));
            OP3.setText(questionDetails.getString(5));
            OP4.setText(questionDetails.getString(6));
            AN.setText(questionDetails.getString(7));
            QID.setEditable(false);                
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Question Id does not Exist!");
        }
            

        } catch (HeadlessException | SecurityException | MalformedURLException | NotBoundException | RemoteException | SQLException e) {
         /*
          * This block will only execute if any  exception occurs in try block
          */
	   JOptionPane.showMessageDialog(null, e);
	} 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        boolean update = false;
        //updating the values

        String id = QID.getText();
        String name = QUES.getText();
        String opt1 = OP1.getText();
        String opt2 = OP2.getText();
        String opt3 = OP3.getText();
        String opt4 = OP4.getText();
        String answer = AN.getText();

        try {
            /*The suspect that this block of statement can throw
            *exception so we handled it by placing these statements
            *inside try and handled the exception in catch block
             */

            Interface a = (Interface) Naming.lookup("rmi://localhost:1099/Server");////It calls naming lookup and url  

            update = a.UpdateQuestion(id, name, opt1, opt2, opt3, opt4, answer);
            if (update == true) {
                int responseUpdate = JOptionPane.showConfirmDialog(this, "Do you want to continue action ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (responseUpdate == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this, "Successfully Updated", "Alert", JOptionPane.WARNING_MESSAGE);
                    JFrame jf = new JFrame();
                    jf.setAlwaysOnTop(true);
                    //JOptionPane.showMessageDialog(jf,"Successfully Updated");
                    setVisible(false);
                    new A_Update_Question().setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Data Updation Cancelled!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Cannot Update Data!", "Failure", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | SecurityException | NotBoundException | RemoteException ex) {
            /*
            * This block will only execute if any  exception occurs in try block
             */
            JOptionPane.showMessageDialog(this, "Error!, " + ex, "Bug!", JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            /*
            * This block will only execute if any  exception occurs in try block
             */
            Logger.getLogger(A_Update_Question.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      // This code segment is used to close  the admin panel
        AdminHomePanel.open=0;
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      //This code segement is to
        QID.setText("");
        QUES.setText("");
        OP1.setText("");
        OP2.setText("");
        OP3.setText("");
        OP4.setText("");
        AN.setText("");
        QID.setEditable(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Delete_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Delete_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Delete_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Delete_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_Update_Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AN;
    private javax.swing.JTextField OP1;
    private javax.swing.JTextField OP2;
    private javax.swing.JTextField OP3;
    private javax.swing.JTextField OP4;
    private javax.swing.JTextField QID;
    private javax.swing.JTextField QUES;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
