/*
 * This is the main user interface from which users can navigate to student and admin panels.
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
package Quiz_Game.rmi.client;

import java.awt.Color;
import java.awt.Point;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Mayu
 */
public class AA_IndexGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form Index2
     */
    public AA_IndexGUI() {
        initComponents();
        
        
    }
    
    Point location;//Point class represents a location in a two-dimensional (x, y) coordinate space.
    Point pressed;
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MathQuiz = new javax.swing.JLabel();
        Student = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        navigation_bar = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        AdminBg = new javax.swing.JLabel();
        StudentBg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(52, 52, 52));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MathQuiz.setBackground(new java.awt.Color(0, 0, 0));
        MathQuiz.setFont(new java.awt.Font("Tempus Sans ITC", 1, 50)); // NOI18N
        MathQuiz.setForeground(new java.awt.Color(255, 255, 255));
        MathQuiz.setText("MATH QUIZ");
        jPanel1.add(MathQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        Student.setFont(new java.awt.Font("Ubuntu Mono", 1, 35)); // NOI18N
        Student.setForeground(new java.awt.Color(255, 255, 255));
        Student.setText("STUDENT");
        Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudentMouseExited(evt);
            }
        });
        jPanel1.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        Admin.setFont(new java.awt.Font("Ubuntu Mono", 1, 35)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("ADMIN");
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminMouseExited(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        navigation_bar.setBackground(new java.awt.Color(0, 0, 0));
        navigation_bar.setPreferredSize(new java.awt.Dimension(985, 35));
        navigation_bar.setRequestFocusEnabled(false);
        navigation_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navigation_barMouseDragged(evt);
            }
        });
        navigation_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigation_barMousePressed(evt);
            }
        });

        Close.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-white-28.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Yu Gothic Light", 0, 50)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-white-28.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout navigation_barLayout = new javax.swing.GroupLayout(navigation_bar);
        navigation_bar.setLayout(navigation_barLayout);
        navigation_barLayout.setHorizontalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigation_barLayout.createSequentialGroup()
                .addContainerGap(539, Short.MAX_VALUE)
                .addComponent(minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Close)
                .addGap(3, 3, 3))
        );
        navigation_barLayout.setVerticalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_barLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(navigation_barLayout.createSequentialGroup()
                        .addComponent(minimize)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(navigation_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        AdminBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student,Admin background.png"))); // NOI18N
        jPanel1.add(AdminBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 290, 90));

        StudentBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student,Admin background.png"))); // NOI18N
        jPanel1.add(StudentBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 290, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MathQuiz-purple-logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 320, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Server_Bg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 610, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentMouseEntered
        //This code segment is used to change the color of the mouse enter event.
        Student.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_StudentMouseEntered

    private void StudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentMouseExited
        //This code segment is used to change the color of the mouse exit event.
        Student.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_StudentMouseExited

    private void navigation_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMousePressed
        //The "mouse pressed" event. This MouseEvent occurs when a mouse button is pushed down.
         pressed = evt.getLocationOnScreen();//Returns the absolute x, y position of the event.
         Window window = SwingUtilities.windowForComponent(evt.getComponent());  //Creating object of Window.
         location = window.getLocation();//Returns the absolute x, y position of the event.
    }//GEN-LAST:event_navigation_barMousePressed

    private void navigation_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMouseDragged
        //The "mouse dragged" event. This MouseEvent occurs when the mouse position changes while a mouse button is pressed.
        Point dragged = evt.getLocationOnScreen(); //Returns the absolute x, y position of the event.
        int x = (int)(location.x + dragged.getX() - pressed.getX());
        int y = (int)(location.y + dragged.getY() - pressed.getY());
        Window window = SwingUtilities.windowForComponent(evt.getComponent());
        window.setLocation(x, y);
 
    }//GEN-LAST:event_navigation_barMouseDragged

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        //This code segment is used to close jframe
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        //This code segment is used to minimize jframe
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseEntered
        // This code segment is used to change the admin forground to black
        Admin.setForeground(new Color(0,0,0));
        
    }//GEN-LAST:event_AdminMouseEntered

    private void AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseExited
        // This code segment is used to change the admin forground to white
        Admin.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_AdminMouseExited

    private void StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentMouseClicked
        // This code segment is used to navigate to Student Panel
         setVisible(false);
         new StudentPanel().setVisible(true);
    }//GEN-LAST:event_StudentMouseClicked

    private void AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseClicked
        // This code segment is used to navigate to AdminLogin Panel
         setVisible(false);
         new AdminLogin().setVisible(true);
    }//GEN-LAST:event_AdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AA_IndexGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AA_IndexGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AA_IndexGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AA_IndexGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AA_IndexGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JLabel AdminBg;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel MathQuiz;
    private javax.swing.JLabel Student;
    private javax.swing.JLabel StudentBg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel navigation_bar;
    // End of variables declaration//GEN-END:variables
}
