/*
 * This is the splash screen
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
package Quiz_Game.rmi.client;

import javax.swing.JOptionPane;

/**
 *
 * @author Mayu
 */
public class AAA_SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form splashScreen
     */
    public AAA_SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MathAppTxt = new javax.swing.JLabel();
        VersionDateTxt = new javax.swing.JLabel();
        SplashScreenBgPanel = new javax.swing.JPanel();
        SplashScreenBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MathAppTxt.setFont(new java.awt.Font("Ubuntu Mono", 0, 50)); // NOI18N
        MathAppTxt.setForeground(new java.awt.Color(255, 255, 255));
        MathAppTxt.setText("Math App");
        getContentPane().add(MathAppTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        VersionDateTxt.setFont(new java.awt.Font("Ubuntu Mono", 0, 25)); // NOI18N
        VersionDateTxt.setForeground(new java.awt.Color(255, 255, 255));
        VersionDateTxt.setText("2021-11");
        getContentPane().add(VersionDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        SplashScreenBgPanel.setBackground(new java.awt.Color(51, 51, 51));
        SplashScreenBgPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        SplashScreenBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SplashScreenBg300.png"))); // NOI18N

        javax.swing.GroupLayout SplashScreenBgPanelLayout = new javax.swing.GroupLayout(SplashScreenBgPanel);
        SplashScreenBgPanel.setLayout(SplashScreenBgPanelLayout);
        SplashScreenBgPanelLayout.setHorizontalGroup(
            SplashScreenBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashScreenBgPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(SplashScreenBg)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        SplashScreenBgPanelLayout.setVerticalGroup(
            SplashScreenBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashScreenBgPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(SplashScreenBg)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(SplashScreenBgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AAA_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AAA_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AAA_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AAA_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        //Creating object to AAA_SplashScreen
        AAA_SplashScreen sp= new AAA_SplashScreen();
        sp.setVisible(true); 
        
        try {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(10);
                if(i==100)
                {
                    sp.setVisible(false); 
                    new AA_IndexGUI().setVisible(true);
                }
        }
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MathAppTxt;
    private javax.swing.JLabel SplashScreenBg;
    private javax.swing.JPanel SplashScreenBgPanel;
    private javax.swing.JLabel VersionDateTxt;
    // End of variables declaration//GEN-END:variables
}
