package Quiz_Game.rmi.client;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * This is the admin panel.
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class AdminHomePanel extends javax.swing.JFrame {
    public static int open=0;

    /**
     * Creates new form AdminHomePanel
     */
    public AdminHomePanel() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AddNewQuestion = new javax.swing.JLabel();
        UpdateQuestion = new javax.swing.JLabel();
        DeleteQuestion = new javax.swing.JLabel();
        AllQuestions = new javax.swing.JLabel();
        AllStudentResults = new javax.swing.JLabel();
        Analytics = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_white_32.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 35));

        jPanel2.setBackground(new java.awt.Color(52, 52, 52));

        AddNewQuestion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        AddNewQuestion.setForeground(new java.awt.Color(255, 255, 255));
        AddNewQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_new question_64.png"))); // NOI18N
        AddNewQuestion.setText("Add New Question");
        AddNewQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewQuestionMouseClicked(evt);
            }
        });

        UpdateQuestion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        UpdateQuestion.setForeground(new java.awt.Color(255, 255, 255));
        UpdateQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update_question_64.png"))); // NOI18N
        UpdateQuestion.setText("Update Question");
        UpdateQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateQuestionMouseClicked(evt);
            }
        });

        DeleteQuestion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        DeleteQuestion.setForeground(new java.awt.Color(255, 255, 255));
        DeleteQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_question_64.png"))); // NOI18N
        DeleteQuestion.setText("Delete Question");
        DeleteQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteQuestionMouseClicked(evt);
            }
        });

        AllQuestions.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        AllQuestions.setForeground(new java.awt.Color(255, 255, 255));
        AllQuestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All_Questions_64.png"))); // NOI18N
        AllQuestions.setText("All Questions");
        AllQuestions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllQuestionsMouseClicked(evt);
            }
        });

        AllStudentResults.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        AllStudentResults.setForeground(new java.awt.Color(255, 255, 255));
        AllStudentResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All_student_results_64.png"))); // NOI18N
        AllStudentResults.setText("All Students Scores");
        AllStudentResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllStudentResultsMouseClicked(evt);
            }
        });

        Analytics.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Analytics.setForeground(new java.awt.Color(255, 255, 255));
        Analytics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analytics-blue-64.png"))); // NOI18N
        Analytics.setText("Analytics");
        Analytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalyticsMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-64.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddNewQuestion)
                .addGap(18, 18, 18)
                .addComponent(UpdateQuestion)
                .addGap(18, 18, 18)
                .addComponent(DeleteQuestion)
                .addGap(18, 18, 18)
                .addComponent(AllQuestions)
                .addGap(35, 35, 35)
                .addComponent(AllStudentResults)
                .addGap(34, 34, 34)
                .addComponent(Analytics, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewQuestion)
                    .addComponent(UpdateQuestion)
                    .addComponent(DeleteQuestion)
                    .addComponent(AllQuestions)
                    .addComponent(AllStudentResults)
                    .addComponent(Analytics)
                    .addComponent(Logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1370, 90));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1370, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewQuestionMouseClicked
        // This code segment to open the AddNewQuestionGUI.
        
        if(open==0)
        {
            new A_AddNewQuestion().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_AddNewQuestionMouseClicked

    private void AnalyticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalyticsMouseClicked
        //This code segment to open the StaticChart GUI where the Quick chart has been implemented.
   
        if(open==0)
        {
            new A_StaticChart().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_AnalyticsMouseClicked

    private void UpdateQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMouseClicked
        // This code segment to open the UpdateQuestionGUI.
        
        if(open==0)
        {
            new A_Update_Question().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_UpdateQuestionMouseClicked

    private void AllQuestionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllQuestionsMouseClicked
        //This code segment to open the AllQuestionGUI.
        
        if(open==0)
        {
            new A_AllQuestion().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_AllQuestionsMouseClicked

    private void DeleteQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMouseClicked
        // This code segment to open the DeleteQuestionGUI.
        
        if(open==0)
        {
            new A_Delete_Question().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_DeleteQuestionMouseClicked

    private void AllStudentResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllStudentResultsMouseClicked
        // This code segment to open the AllStudentsScoresGUI.
        
        if(open==0)
        {
            new A_AllStudentsScores().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_AllStudentResultsMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        //This code segment to logout
        
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        int a=JOptionPane.showConfirmDialog(jf,"Do you really want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new AA_IndexGUI().setVisible(true);
        }
       
      
    }//GEN-LAST:event_LogoutMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        //This code segment to close the jframe.
         System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewQuestion;
    private javax.swing.JLabel AllQuestions;
    private javax.swing.JLabel AllStudentResults;
    private javax.swing.JLabel Analytics;
    private javax.swing.JLabel DeleteQuestion;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel UpdateQuestion;
    private javax.swing.JLabel close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
