package Quiz_Game.rmi.client;

import java.awt.Point;
import java.awt.Window;
import javax.swing.SwingUtilities;

/*
 * This program is to show the quiz's score.
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class QuizGameStudentScore extends javax.swing.JFrame {
    
      Point location;//Point class represents a location in a two-dimensional (x, y) coordinate space.
      Point pressed;

    /**
     * Creates new form QuizGameStudentResults
     */
    public QuizGameStudentScore(){
        initComponents();
           
    }
      /***
       * This code segment to get the marks from QuizGameGUI
       * @param marks 
       */
      public QuizGameStudentScore(String marks) {
        initComponents();
        int m=Integer.parseInt(marks);  
        
        if(m>7){
            t1.setText("WoW...nice..");
            t2.setText("congratulation");     
            jLabel1.setText(String.valueOf(m));
           
           
        }
        else if(m>3 && m<8){
            t1.setText("nice try..");
            t2.setText("congratulation");
            jLabel1.setText(String.valueOf(m));
            
            
        }
        else{
            t1.setText("Sorry...");
            t2.setText("try next time");
            jLabel1.setText(String.valueOf(m));
        }
       
    }
      
     
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigation_bar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        purple_leaf = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation_bar.setBackground(new java.awt.Color(0, 0, 0));
        navigation_bar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(153, 51, 255)));
        navigation_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navigation_barMouseDragged(evt);
            }
        });
        navigation_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigation_barMousePressed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-white-28.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navigation_barLayout = new javax.swing.GroupLayout(navigation_bar);
        navigation_bar.setLayout(navigation_barLayout);
        navigation_barLayout.setHorizontalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigation_barLayout.createSequentialGroup()
                .addGap(0, 560, Short.MAX_VALUE)
                .addComponent(close))
        );
        navigation_barLayout.setVerticalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_barLayout.createSequentialGroup()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(navigation_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 32));

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 52, 52));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        jPanel1.setForeground(new java.awt.Color(211, 22, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Ubuntu Mono", 0, 25)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 411, 25));

        t2.setFont(new java.awt.Font("Ubuntu Mono", 0, 25)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 411, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("9");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 40, 30));

        purple_leaf.setForeground(new java.awt.Color(255, 255, 0));
        purple_leaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purple_leaf_150.png"))); // NOI18N
        purple_leaf.setText("jLabel1");
        jPanel1.add(purple_leaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, 90));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 490, 240));

        jPanel3.setBackground(new java.awt.Color(153, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 80, 80));

        jPanel4.setBackground(new java.awt.Color(114, 83, 223));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 130, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 590, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new StudentPanel().setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    private void navigation_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMousePressed
        //The "mouse pressed" event. This MouseEvent occurs when a mouse button is pushed down.
         pressed = evt.getLocationOnScreen();//Returns the absolute x, y position of the event.
         Window window = SwingUtilities.windowForComponent(evt.getComponent());  //Creating object of Window.
         location = window.getLocation();//Returns the absolute x, y position of the event.
    }//GEN-LAST:event_navigation_barMousePressed

    private void navigation_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMouseDragged
       //The "mouse dragged" event. This MouseEvent occurs when the mouse position changes while a mouse button is pressed.
        Point dragged = evt.getLocationOnScreen(); //Returns the absolute x, y position of the event.
        int x = (int)(location.x + dragged.getX() - pressed.getX());
        int y = (int)(location.y + dragged.getY() - pressed.getY());
        Window window = SwingUtilities.windowForComponent(evt.getComponent());
        window.setLocation(x, y);
    }//GEN-LAST:event_navigation_barMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGameStudentScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGameStudentScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGameStudentScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGameStudentScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGameStudentScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel navigation_bar;
    private javax.swing.JLabel purple_leaf;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    // End of variables declaration//GEN-END:variables
}
