package Quiz_Game.rmi.client;

import Quiz_Game.Interface.Interface;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Window;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/*
 * This program is to take the students' details before they take the quiz.  
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class QuizEntryDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    Point location;//Point class represents a location in a two-dimensional (x, y) coordinate space.
    Point pressed;
    
    public QuizEntryDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigation_bar = new javax.swing.JPanel();
        CloseBtn = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        FillTheFormBg = new javax.swing.JPanel();
        FillTheForm = new javax.swing.JLabel();
        Clear = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Save_Next = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        RN = new javax.swing.JLabel();
        age_textfield = new javax.swing.JTextField();
        A = new javax.swing.JLabel();
        Gender_textfield = new javax.swing.JTextField();
        G = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        name_textfield = new javax.swing.JTextField();
        rollnumber_textfield = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation_bar.setBackground(new java.awt.Color(0, 0, 0));
        navigation_bar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(153, 51, 255)));
        navigation_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navigation_barMouseDragged(evt);
            }
        });
        navigation_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigation_barMousePressed(evt);
            }
        });

        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-white-28.png"))); // NOI18N
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back-white-28.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-white-28.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navigation_barLayout = new javax.swing.GroupLayout(navigation_bar);
        navigation_bar.setLayout(navigation_barLayout);
        navigation_barLayout.setHorizontalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_barLayout.createSequentialGroup()
                .addGap(0, 420, Short.MAX_VALUE)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseBtn))
        );
        navigation_barLayout.setVerticalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_barLayout.createSequentialGroup()
                .addComponent(CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(navigation_barLayout.createSequentialGroup()
                .addGroup(navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Minimize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(navigation_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        FillTheFormBg.setBackground(new java.awt.Color(41, 41, 41));
        FillTheFormBg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        FillTheFormBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FillTheForm.setBackground(new java.awt.Color(255, 255, 255));
        FillTheForm.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        FillTheForm.setForeground(new java.awt.Color(255, 255, 255));
        FillTheForm.setText("FILL THE FORM");
        FillTheFormBg.add(FillTheForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 200, 30));

        Clear.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("CLEAR");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        FillTheFormBg.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 60, -1));

        jPanel2.setBackground(new java.awt.Color(114, 83, 223));

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FillTheFormBg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 80, 80));

        jPanel3.setBackground(new java.awt.Color(52, 52, 52));

        Save_Next.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        Save_Next.setForeground(new java.awt.Color(255, 255, 255));
        Save_Next.setText("SAVE & NEXT");
        Save_Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Save_NextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save_Next)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Save_Next)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FillTheFormBg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 140, 20));

        jPanel4.setBackground(new java.awt.Color(52, 52, 52));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        FillTheFormBg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 90, 20));

        jPanel6.setBackground(new java.awt.Color(52, 52, 52));

        RN.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        RN.setForeground(new java.awt.Color(255, 255, 255));
        RN.setText("ROLL NUMBER");

        age_textfield.setBackground(new java.awt.Color(52, 52, 52));
        age_textfield.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        age_textfield.setForeground(new java.awt.Color(255, 255, 255));
        age_textfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        age_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_textfieldActionPerformed(evt);
            }
        });

        A.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("AGE");

        Gender_textfield.setBackground(new java.awt.Color(52, 52, 52));
        Gender_textfield.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        Gender_textfield.setForeground(new java.awt.Color(255, 255, 255));
        Gender_textfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        G.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        G.setForeground(new java.awt.Color(255, 255, 255));
        G.setText("GENDER");

        N.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        N.setForeground(new java.awt.Color(255, 255, 255));
        N.setText("NAME");

        name_textfield.setBackground(new java.awt.Color(52, 52, 52));
        name_textfield.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        name_textfield.setForeground(new java.awt.Color(255, 255, 255));
        name_textfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        rollnumber_textfield.setBackground(new java.awt.Color(52, 52, 52));
        rollnumber_textfield.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        rollnumber_textfield.setForeground(new java.awt.Color(255, 255, 255));
        rollnumber_textfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(G)
                            .addGap(103, 103, 103))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(118, 118, 118))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gender_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rollnumber_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(RN))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(N)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(RN)
                .addGap(18, 18, 18)
                .addComponent(rollnumber_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(N)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(G)
                .addGap(18, 18, 18)
                .addComponent(Gender_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(A)
                .addGap(18, 18, 18)
                .addComponent(age_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        FillTheFormBg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, 430));

        jPanel5.setBackground(new java.awt.Color(52, 52, 52));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        FillTheFormBg.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, 30));

        getContentPane().add(FillTheFormBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void age_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_textfieldActionPerformed

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        // This code segment is to close the QuizEntryDetails jframe
           System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked
    
    /***
     * This event to get the students results
     * @param evt 
     */
    private void Save_NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save_NextMouseClicked

        boolean result;
        
        //getting user data's from textfield.
        String rollnumber = rollnumber_textfield.getText();
        String name = name_textfield.getText();
        String gender = Gender_textfield.getText();
        String age = age_textfield.getText();
        String marks = "0";
          
        if(rollnumber.isEmpty() && name.isEmpty() && gender.isEmpty() && age.isEmpty() )//Checking whether all fields are filled fully
        {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");//If all the fields are empty, this messeged will be displayed
        }
        else if(rollnumber.isEmpty())//check whether the rollnumber is entered
        {
            JOptionPane.showMessageDialog(null, "Please fill the roll number");//If the roll number is not entered, this messeged will be displayed.
        }
        else if(name.isEmpty())//check whether the name is entered
        {
            JOptionPane.showMessageDialog(null, "Please fill the name");//If the name is not entered, this messeged will be displayed.
        }
        else if(gender.isEmpty())//check whether the gender is entered
        {
            JOptionPane.showMessageDialog(null, "Please fill gender");//If the gender is not entered, this messeged will be displayed.
        }
        else if(age.isEmpty())//check whether the age is entered
        {
            JOptionPane.showMessageDialog(null, "Please fill age");//If age is not entered, this messeged will be displayed.
        }
        else
        {
        /***
         * If the all fields are entered, all data will be saved to the database
         */
        try {
            /* The suspect that this block of statement can throw 
             * exception so we handled it by placing these statements
             * inside try and handled the exception in catch block
             */

            Interface a = (Interface) Naming.lookup("rmi://localhost:1099/Server"); //It calls naming lookup and url  
            result = a.studentlogin(rollnumber, name, gender, age, marks);
            if (result = true) {
                setVisible(false);
                new S_InstructionStudent(rollnumber).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Something wrong", "Unable to enter into quiz", 2);
            }

            /*
        * This block will only execute if any  exception occurs in try block
             */
        } catch (HeadlessException | NotBoundException | RemoteException ex) {
            JOptionPane.showMessageDialog(null, "" + ex);

            /* This block will only execute if any Arithmetic exception 
             * occurs in try block
             */
        } catch (MalformedURLException ex) {
            Logger.getLogger(QuizEntryDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      }

    }//GEN-LAST:event_Save_NextMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
         setVisible(false);
         new StudentPanel().setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
         setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void navigation_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMouseDragged
        //The "mouse dragged" event. This MouseEvent occurs when the mouse position changes while a mouse button is pressed.
        Point dragged = evt.getLocationOnScreen(); //Returns the absolute x, y position of the event.
        int x = (int)(location.x + dragged.getX() - pressed.getX());
        int y = (int)(location.y + dragged.getY() - pressed.getY());
        Window window = SwingUtilities.windowForComponent(evt.getComponent());
        window.setLocation(x, y);
    }//GEN-LAST:event_navigation_barMouseDragged

    private void navigation_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMousePressed
        //The "mouse pressed" event. This MouseEvent occurs when a mouse button is pushed down.
         pressed = evt.getLocationOnScreen();//Returns the absolute x, y position of the event.
         Window window = SwingUtilities.windowForComponent(evt.getComponent());  //Creating object of Window.
         location = window.getLocation();//Returns the absolute x, y position of the event.
    }//GEN-LAST:event_navigation_barMousePressed

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        // This code segment to clear fields
         rollnumber_textfield.setText("");
         name_textfield.setText("");
         Gender_textfield.setText("");
         age_textfield.setText("");
        
        
    }//GEN-LAST:event_ClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizEntryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizEntryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizEntryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizEntryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizEntryDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Clear;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JLabel FillTheForm;
    private javax.swing.JPanel FillTheFormBg;
    private javax.swing.JLabel G;
    private javax.swing.JTextField Gender_textfield;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel N;
    private javax.swing.JLabel RN;
    private javax.swing.JLabel Save_Next;
    private javax.swing.JTextField age_textfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JPanel navigation_bar;
    private javax.swing.JTextField rollnumber_textfield;
    // End of variables declaration//GEN-END:variables
}
