package Quiz_Game.rmi.client;

import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Window;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * This program is to send the S_ContactUs using java mail
 * Activation.jar and javax.mail.jar have been used.
 * I studied the way to send mail using smtp in https://www.javatpoint.com
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class S_ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form feedback
     */
    public S_ContactUs() {
        initComponents();
    }
    
    Point location;//Point class represents a location in a two-dimensional (x, y) coordinate space.
    Point pressed; 
    
    public static void send(String from,String password,String to,String sub,String msg){  
          //Get properties object    
          Properties props = new Properties();    
          props.put("mail.smtp.host", "smtp.gmail.com");    
          props.put("mail.smtp.socketFactory.port", "465");    
          props.put("mail.smtp.socketFactory.class",    
                    "javax.net.ssl.SSLSocketFactory");    
          props.put("mail.smtp.auth", "true");    
          props.put("mail.smtp.port", "465");    
          //get Session   
          Session session = Session.getDefaultInstance(props,    
          new javax.mail.Authenticator() {    
          protected PasswordAuthentication getPasswordAuthentication() {    
          return new PasswordAuthentication(from,password);  
           }    
          });    
          //compose message    
          try {    
           MimeMessage message = new MimeMessage(session);    
           message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));    
              
           message.setSubject(sub);    
           message.setText(msg);    
           //send message  
           Transport.send(message);    
           System.out.println("message sent successfully");    
          } catch (MessagingException e) {throw new RuntimeException(e);}    
             
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigation_bar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ContactUsBG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComplaintSubject = new javax.swing.JLabel();
        ComplaintDetails = new javax.swing.JLabel();
        Complaint_Subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Complaint_Details = new javax.swing.JTextArea();
        Send_Mail = new javax.swing.JLabel();
        Clear = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation_bar.setBackground(new java.awt.Color(0, 0, 0));
        navigation_bar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        navigation_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navigation_barMouseDragged(evt);
            }
        });
        navigation_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigation_barMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-white-28.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-white-28.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back-white-28.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navigation_barLayout = new javax.swing.GroupLayout(navigation_bar);
        navigation_bar.setLayout(navigation_barLayout);
        navigation_barLayout.setHorizontalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigation_barLayout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );
        navigation_barLayout.setVerticalGroup(
            navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_barLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(navigation_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(navigation_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        ContactUsBG.setBackground(new java.awt.Color(41, 41, 41));
        ContactUsBG.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ContactUsBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(52, 52, 52));
        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Contact Us");
        ContactUsBG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 41, 282, -1));

        ComplaintSubject.setFont(new java.awt.Font("Ubuntu Mono", 0, 22)); // NOI18N
        ComplaintSubject.setForeground(new java.awt.Color(255, 255, 255));
        ComplaintSubject.setText("Roll Number");
        ContactUsBG.add(ComplaintSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 170, 129, -1));

        ComplaintDetails.setFont(new java.awt.Font("Ubuntu Mono", 0, 22)); // NOI18N
        ComplaintDetails.setForeground(new java.awt.Color(255, 255, 255));
        ComplaintDetails.setText("Messege");
        ContactUsBG.add(ComplaintDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, -1));

        Complaint_Subject.setBackground(new java.awt.Color(52, 52, 52));
        Complaint_Subject.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        Complaint_Subject.setForeground(new java.awt.Color(255, 255, 255));
        Complaint_Subject.setBorder(null);
        ContactUsBG.add(Complaint_Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 211, 330, -1));

        Complaint_Details.setBackground(new java.awt.Color(52, 52, 52));
        Complaint_Details.setColumns(20);
        Complaint_Details.setFont(new java.awt.Font("Ubuntu Mono", 0, 20)); // NOI18N
        Complaint_Details.setForeground(new java.awt.Color(255, 255, 255));
        Complaint_Details.setRows(5);
        Complaint_Details.setBorder(null);
        jScrollPane1.setViewportView(Complaint_Details);

        ContactUsBG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 309, 330, -1));

        Send_Mail.setFont(new java.awt.Font("Ubuntu Mono", 0, 25)); // NOI18N
        Send_Mail.setForeground(new java.awt.Color(255, 255, 255));
        Send_Mail.setText("Send");
        Send_Mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Send_MailMouseClicked(evt);
            }
        });
        ContactUsBG.add(Send_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 459, 70, -1));

        Clear.setFont(new java.awt.Font("Ubuntu Mono", 0, 25)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        ContactUsBG.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jPanel2.setBackground(new java.awt.Color(114, 83, 223));

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ContactUsBG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        jPanel3.setBackground(new java.awt.Color(52, 52, 52));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        ContactUsBG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 70));

        jPanel4.setBackground(new java.awt.Color(52, 52, 52));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ContactUsBG.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 90, 30));

        jPanel5.setBackground(new java.awt.Color(52, 52, 52));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ContactUsBG.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 90, 30));

        getContentPane().add(ContactUsBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Send_MailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Send_MailMouseClicked
        // This code segment is to send the mail
       
      //getting user details in variables  
      String sub = Complaint_Subject.getText();
      String msg =  Complaint_Details.getText();
      
      if(sub.isEmpty() && msg.isEmpty())//check whether rollnumber and complaint fields are filled
        {
            JOptionPane.showMessageDialog(null, "rollnumber and complaints can't be empty");//Show the dialog box if the rollnumber and complaints are empty.
        }
      else if(sub.isEmpty())//Check whether rollnumber is filled.
        {
            JOptionPane.showMessageDialog(null, "Rollnumber can't be empty");//Show the dialog box if the rollnumber is empty.
        }
      else if(msg.isEmpty())//Check whether rollnumber is filled.
        {
            JOptionPane.showMessageDialog(null, "messege can't be empty");//Show the dialog box if the messege is empty.
        }
      else
      {
      try {
          
      /* The suspect that this block of statement can throw 
       * exception so we handled it by placing these statements
       * inside try and handled the exception in catch block
       */
      String to ="thisisforsoftwareengineering@gmail.com";
      String from = "UOB.SLIIT.SMTP@gmail.com";
      String password = "Smtp-Uob-123";    
              
      S_ContactUs.send(from,password, to, sub, msg); 
           
      
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Mail have been sent");
            setVisible(false);
            new S_ContactUs().setVisible(true);
            
        } catch (HeadlessException | SecurityException e) {
           /*
            *This block will only execute if any  exception occurs in try block
            */
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
            
        }
      }
    }//GEN-LAST:event_Send_MailMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        // This code segments to clear textfield
         Complaint_Subject.setText("");
         Complaint_Details.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void navigation_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMousePressed
        //The "mouse pressed" event. This MouseEvent occurs when a mouse button is pushed down.
         pressed = evt.getLocationOnScreen();//Returns the absolute x, y position of the event.
         Window window = SwingUtilities.windowForComponent(evt.getComponent());  //Creating object of Window.
         location = window.getLocation();//Returns the absolute x, y position of the event.
    }//GEN-LAST:event_navigation_barMousePressed

    private void navigation_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMouseDragged
       //The "mouse dragged" event. This MouseEvent occurs when the mouse position changes while a mouse button is pressed.
        Point dragged = evt.getLocationOnScreen(); //Returns the absolute x, y position of the event.
        int x = (int)(location.x + dragged.getX() - pressed.getX());
        int y = (int)(location.y + dragged.getY() - pressed.getY());
        Window window = SwingUtilities.windowForComponent(evt.getComponent());
        window.setLocation(x, y);

    }//GEN-LAST:event_navigation_barMouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //This code segment is to close the ContactUs GUI
         setVisible(false);
         new AA_IndexGUI().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //This code segement is to minimize the ContactUs GUI
         setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        //This code segment is to go to students panel
         setVisible(false);
         new StudentPanel().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clear;
    private javax.swing.JLabel ComplaintDetails;
    private javax.swing.JLabel ComplaintSubject;
    private javax.swing.JTextArea Complaint_Details;
    private javax.swing.JTextField Complaint_Subject;
    private javax.swing.JPanel ContactUsBG;
    private javax.swing.JLabel Send_Mail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navigation_bar;
    // End of variables declaration//GEN-END:variables

    private Message prepareMessage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
