package Quiz_Game.rmi.client;

import java.awt.Color;
import java.awt.Point;
import java.awt.Window;
import javax.swing.SwingUtilities;

/*
 * This program is to show the instructions to students before they take the quiz.
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class S_InstructionStudent extends javax.swing.JFrame {
    
    public String rollNo;
   
    /**
     * Creates new form instuctionStudent
     */
    public S_InstructionStudent() {
        initComponents();
       // Instruction_textArea.setEditable(false);
    }
      
    /***
     * This method is to get roll number from QuizEntryDetails GUI.
     * @param rollNo1 
     */   
    public S_InstructionStudent(String rollNo1) {
        initComponents();
          //JOptionPane.showMessageDialog(null, rollNo1);
          rollNo=rollNo1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InstructionHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        StartQuizBtn = new javax.swing.JLabel();
        InstructionBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 52, 52));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(643, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstructionHeader.setFont(new java.awt.Font("Ubuntu Mono", 0, 30)); // NOI18N
        InstructionHeader.setForeground(new java.awt.Color(255, 255, 255));
        InstructionHeader.setText("INSTRUCTIONS");
        jPanel1.add(InstructionHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quiz Duration : 10 mins");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Each Question carries 1 score");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Multiple-choice question");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("closed book quiz");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("There shall be no negative marking");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Number of Questions :10");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(227, 188, 136));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 1, new java.awt.Color(96, 37, 20)));

        StartQuizBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        StartQuizBtn.setText("START QUIZ");
        StartQuizBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StartQuizBtnFocusGained(evt);
            }
        });
        StartQuizBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartQuizBtnMouseClicked(evt);
            }
        });
        jPanel2.add(StartQuizBtn);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 150, 35));

        InstructionBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InstructionBg2.png"))); // NOI18N
        jPanel1.add(InstructionBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 430, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartQuizBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartQuizBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new QuizGameGUI(rollNo).setVisible(true);
    }//GEN-LAST:event_StartQuizBtnMouseClicked

    private void StartQuizBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StartQuizBtnFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StartQuizBtnFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_InstructionStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InstructionBg;
    private javax.swing.JLabel InstructionHeader;
    private javax.swing.JLabel StartQuizBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
