package Quiz_Game.rmi.client;

import java.awt.Point;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class StudentPanel extends javax.swing.JFrame {
    
    Point location; //Point class represents a location in a two-dimensional (x, y) coordinate space.
    Point pressed;

    /**
     * Creates new form Student
     */
    public StudentPanel() {
        initComponents();
        
         Light_1.setVisible(false);
         Light_2.setVisible(false);
         Light_3.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        HighScoreBtn = new javax.swing.JLabel();
        ContactUsBtn = new javax.swing.JLabel();
        StartQuizBtn = new javax.swing.JLabel();
        Light_1 = new javax.swing.JLabel();
        Light_2 = new javax.swing.JLabel();
        Light_3 = new javax.swing.JLabel();
        StudentPanel_Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back-white-28.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-white-28.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-white-28.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Minimize)
                    .addComponent(Close))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        HighScoreBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 35)); // NOI18N
        HighScoreBtn.setForeground(new java.awt.Color(255, 255, 255));
        HighScoreBtn.setText("High Scores");
        HighScoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HighScoreBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HighScoreBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HighScoreBtnMouseExited(evt);
            }
        });
        getContentPane().add(HighScoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        ContactUsBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 35)); // NOI18N
        ContactUsBtn.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsBtn.setText("Contact Us");
        ContactUsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContactUsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContactUsBtnMouseExited(evt);
            }
        });
        getContentPane().add(ContactUsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        StartQuizBtn.setFont(new java.awt.Font("Ubuntu Mono", 1, 35)); // NOI18N
        StartQuizBtn.setForeground(new java.awt.Color(255, 255, 255));
        StartQuizBtn.setText("Start Quiz");
        StartQuizBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartQuizBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartQuizBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartQuizBtnMouseExited(evt);
            }
        });
        getContentPane().add(StartQuizBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        Light_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Light_2.png"))); // NOI18N
        getContentPane().add(Light_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 60, 70));

        Light_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Light_2.png"))); // NOI18N
        getContentPane().add(Light_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 60, 60));

        Light_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Light_2.png"))); // NOI18N
        getContentPane().add(Light_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 60, 60));

        StudentPanel_Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StudentPanel_Bg.jpg"))); // NOI18N
        StudentPanel_Bg.setText("jLabel1");
        StudentPanel_Bg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(StudentPanel_Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        //This code segment is to close Student Panel GUI.
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        //This code segment is to go to IndexGUI.
         setVisible(false);
         new AA_IndexGUI().setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        //This code segment is to minimize the StudentPanel.
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void StartQuizBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartQuizBtnMouseClicked
        //This code segment is to go to QuizEntryDetails gui.
         setVisible(false);
         new QuizEntryDetails().setVisible(true);
    }//GEN-LAST:event_StartQuizBtnMouseClicked

    private void HighScoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HighScoreBtnMouseClicked
        //This code segment is to go to HighScores gui.
         setVisible(false);
         new S_HighScores().setVisible(true);
    }//GEN-LAST:event_HighScoreBtnMouseClicked

    private void ContactUsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsBtnMouseClicked
        //This code segment is to go to ContactUs gui.
         setVisible(false);
         new S_ContactUs().setVisible(true);
    }//GEN-LAST:event_ContactUsBtnMouseClicked

    private void StartQuizBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartQuizBtnMouseEntered
        //The "mouse entered" event. This MouseEvent occurs when the mouse cursor enters the unobscured part of component's geometry
        Light_1.setVisible(true);//Showing light icon      
    }//GEN-LAST:event_StartQuizBtnMouseEntered

    private void StartQuizBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartQuizBtnMouseExited
        //The "mouse exited" event. This MouseEvent occurs when the mouse cursor exits the unobscured part of component's geometry.
        Light_1.setVisible(false);//Hiding light icon
    }//GEN-LAST:event_StartQuizBtnMouseExited

    private void HighScoreBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HighScoreBtnMouseEntered
        //The "mouse entered" event. This MouseEvent occurs when the mouse cursor enters the unobscured part of component's geometry
        Light_2.setVisible(true);//Showing light icon
                                  
    }//GEN-LAST:event_HighScoreBtnMouseEntered

    private void HighScoreBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HighScoreBtnMouseExited
        //The "mouse exited" event. This MouseEvent occurs when the mouse cursor exits the unobscured part of component's geometry.
        Light_2.setVisible(false);//Hiding light icon
    }//GEN-LAST:event_HighScoreBtnMouseExited

    private void ContactUsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsBtnMouseEntered
        //The "mouse entered" event. This MouseEvent occurs when the mouse cursor enters the unobscured part of component's geometry
        Light_3.setVisible(true);//Showing light icon
    }//GEN-LAST:event_ContactUsBtnMouseEntered

    private void ContactUsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsBtnMouseExited
        //The "mouse exited" event. This MouseEvent occurs when the mouse cursor exits the unobscured part of component's geometry.
        Light_3.setVisible(false); //Hiding light icon
    }//GEN-LAST:event_ContactUsBtnMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        //The "mouse pressed" event. This MouseEvent occurs when a mouse button is pushed down.
         pressed = evt.getLocationOnScreen();//Returns the absolute x, y position of the event.
         Window window = SwingUtilities.windowForComponent(evt.getComponent());  //Creating object of Window.
         location = window.getLocation();//Returns the absolute x, y position of the event.
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        //The "mouse dragged" event. This MouseEvent occurs when the mouse position changes while a mouse button is pressed.
        Point dragged = evt.getLocationOnScreen(); //Returns the absolute x, y position of the event.
        int x = (int)(location.x + dragged.getX() - pressed.getX());
        int y = (int)(location.y + dragged.getY() - pressed.getY());
        Window window = SwingUtilities.windowForComponent(evt.getComponent());
        window.setLocation(x, y);

    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel ContactUsBtn;
    private javax.swing.JLabel HighScoreBtn;
    private javax.swing.JLabel Light_1;
    private javax.swing.JLabel Light_2;
    private javax.swing.JLabel Light_3;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel StartQuizBtn;
    private javax.swing.JLabel StudentPanel_Bg;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
